### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jbbpatel94**

### CODE REVIEW

**Comment by mathiasvr** [comment]
The brackets are there to show that the parameter is optional.

**Comment by jbbpatel94** [comment]
Yes, but it seems like array.

**Comment by mathiasvr** [comment]
Maybe it should be made more clear, but I think brackets for optional parameters are fairly well known.

**Comment by jbbpatel94** [comment]
Yes, you are right. It should be made more clear.
[Here stackoverflow ](https://stackoverflow.com/questions/37691490/square-brackets-surrounding-parameter-in-function-definition)

**Comment by mathiasvr** [comment]
Hm, I see the new ES destructuring syntax can make this more confusing.

Okay, I think it's alright to remove the brackets in this case.

**Pull request merged**
